### ISSUE TITLE
revocation check for domains with a hyphen

### ISSUE THREAD

**Issue by tordensen** [o-pod/security#1]
hi.
options parser breaks domains with the "-" character.
my-site.org becomes mysite.org etc

`    domain=$(echo ${*} | sed 's/\-[a-z]//gi' | sed 's/ //g')`
should be
`    domain=$(echo ${*} | sed 's/\-\b[a-z]\b//gi' | sed 's/ //g')`

**Comment by o-pod** [comment]
Thanks, [tordensen](https://github.com/tordensen).
The bug was fixed in https://github.com/o-pod/security/commit/293a52a17c7c8564939b6dba5e6019c15016edf5.
